# Generated by Django 5.1 on 2025-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('eligibility_status', models.BooleanField(default=True)),
            ],
        ),
    ]
