# Generated by Django 5.1 on 2025-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_donated', models.PositiveIntegerField()),
                ('donation_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
